# Personalized modified version of Hugo theme Blowfish

name = "iA-Blowfish"
license = "MIT"
licenselink = "https://github.com/imwqqa/ia-blowfish/blob/main/LICENSE"
description = "A tiny personalized modified version of theme Blowfish."

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax highlighting", "dark mode", "emoji", "firebase", "views"]

[author]
  name = "imwqqa"

[upstream]
  name = "Nuno Coracao"
  homepage = "https://n9o.xyz/"
  repo = "https://github.com/nunocoracao/blowfish/"

[original]
  author = "James Panther"
  homepage = "https://jamespanther.com/"
  repo = "https://github.com/jpanther/congo"
